name = "visu"
uuid = "0c4a955f-c96d-4def-a045-4cfb171523c1"
authors = ["Marc Lelarge <marc.lelarge@gmail.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
